name = "dark-chat"
main = "worker.js"
compatibility_date = "2026-03-01"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[[d1_databases]]
binding = "DB"
database_name = "chat-db"
database_id = "4b86b503-f438-4a45-b5a6-b868a7467eae"

[assets]
directory = "./public"
